// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDQQDSUMbK9FQxWYlWbrA8tZKA-J2nSESU',
    appId: '1:885361190787:web:95f8f6a494698335c078b6',
    messagingSenderId: '885361190787',
    projectId: 'fintrackernew',
    authDomain: 'fintrackernew.firebaseapp.com',
    storageBucket: 'fintrackernew.appspot.com',
    measurementId: 'G-VL825J3RG9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCglN7LyMxtLa3u9U5s0GXh1DqxqdSqIUs',
    appId: '1:885361190787:android:43223a81ddee6449c078b6',
    messagingSenderId: '885361190787',
    projectId: 'fintrackernew',
    storageBucket: 'fintrackernew.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBGAzObRa-lRxdjIVs3O-jap6mlTImbnbE',
    appId: '1:885361190787:ios:446f07597c6066aec078b6',
    messagingSenderId: '885361190787',
    projectId: 'fintrackernew',
    storageBucket: 'fintrackernew.appspot.com',
    iosClientId: '885361190787-0hb3ldcsoejuushq1omo1vcs2qcejq85.apps.googleusercontent.com',
    iosBundleId: 'com.example.fintrackernew',
  );
}
